### ISSUE TITLE
[ANDROID] requesting for ecg stream settings error & unable to start multiple stream

### ISSUE THREAD

**Issue by kc1rt4p** [Rexios80/polar#13]
![image](https://user-images.githubusercontent.com/25317992/205482096-4fc0b070-6fe7-45fd-a851-7e5505d20c23.png)

This happens when I request stream setting for ECG.

Can I stream all data from a device concurrently? I've tried and only 1 stream is able to provide data at a time

**Comment by kc1rt4p** [comment]
yes I'm waiting for `polar.streamingFeaturesReadyStream`, here's the snippet of the code:

```
polar.streamingFeaturesReadyStream.listen((event) {
      final features = event.features.map((f) => f.name.toLowerCase());

      if (features.contains('acc')) {
        print('=== ACC is READY');
        startACCstream();
      }

      if (features.contains('gyro')) {
        print('=== GYRO is READY');
        startGyroStream();
      }

      if (features.contains('magnetometer')) {
        print('=== MAGNETOMETER is READY');
        startMagnetometerStream();
      }

      if (features.contains('ppg')) {
        print('=== PPG is READY');
        startPPGstream();
      }

      if (features.contains('ppi')) {
        print('=== PPI is READY');
        startPPIstream();
      }
    }, onDone: () {
      print('streaming features ready - DONE');
    });
```
I tried running 1 stream at a time, it works except for ECG since I'm getting the error that I mentioned.

I removed the requestStreamSetting for ecg but the error still occurred, probably because the plugin does it already like you said.

I'm trying to stream multiple data since my app needs every 15 sec interval

**Comment by kc1rt4p** [comment]
I've check the logs on why it only stream the first feature on the ready list (event.features)

the error says `failed to close existing event stream` when I try to start the other stream

**Comment by Rexios80** [comment]
Apparently I didn't know how EventChannels work 🙃. I fixed this issue, but I'm dealing with others that came up after. I hope to have everything working soon.

**Comment by Rexios80** [comment]
I just released version 3.5.0 which should fix this

**Comment by Rexios80** [comment]
Although I do notice that code snippet you gave has every feature except ecg in it

**Comment by kc1rt4p** [comment]
> Although I do notice that code snippet you gave has every feature except ecg in it

Oh, I removed it after I got the error

> I just released version 3.5.0 which should fix this

Thank you very much sir, will try the new version

**Comment by kc1rt4p** [comment]
I'm able to run multiple stream now. 

I already removed all request stream settings

still getting this error when I ran `polar.startEcgStreaming`
```
E/flutter (19436): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(com.polar.sdk.api.errors.PolarNotificationNotEnabled, null, null, null)
E/flutter (19436): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter (19436): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter (19436): <asynchronous suspension>
E/flutter (19436): #2      Polar.requestStreamSettings
package:polar/src/polar_base.dart:251
E/flutter (19436): <asynchronous suspension>
E/flutter (19436): #3      Polar._startStreaming
package:polar/src/polar_base.dart:272
E/flutter (19436): <asynchronous suspension>
```

and this error when running `polar.startOhrPPIStreaming`

```
E/flutter (19436): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(com.polar.androidcommunications.api.ble.exceptions.BleControlPointCommandError: pmd cp command error:  failed with error: ERROR_INVALID_MEASUREMENT_TYPE, pmd cp command error:  failed with error: ERROR_INVALID_MEASUREMENT_TYPE, null, null)
E/flutter (19436): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter (19436): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter (19436): <asynchronous suspension>
E/flutter (19436): #2      Polar.requestStreamSettings
package:polar/src/polar_base.dart:251
E/flutter (19436): <asynchronous suspension>
E/flutter (19436): #3      Polar._startStreaming
package:polar/src/polar_base.dart:272
E/flutter (19436): <asynchronous suspension>
```

**Comment by Rexios80** [comment]
If you're using an H10 it needs a firmware update to support ECG streaming

**Comment by Rexios80** [comment]
I fixed PPI streaming in version 3.7.0

**Comment by kc1rt4p** [comment]
> What polar device are you using?

Verity Sense and OH1



> I fixed PPI streaming in version 3.7.0

Thanks!

**Comment by kc1rt4p** [comment]
ECG is not streamed as feature ready on `polar.streamingFeaturesReadyStream`

**Comment by Rexios80** [comment]
Are you sure those devices support ecg streaming? If it's not showing up in the ready streaming features then it's probably not supported by the device

**Comment by kc1rt4p** [comment]
> Are you sure those devices support ecg streaming? If it's not showing up in the ready streaming features then it's probably not supported by the device

They actually don't, so that's why. heh

I really appreciate your help, the issue is resolved

May the force be with you
